SUL23-39 | @jdwjdwjdw | Build "Event Series" content display
SU-SWS/sulgryphon-nextjs pull request #39
Opened 2022-11-29 23:01 UTC by jdwjdwjdw

# NOT READY FOR REVIEW

# Summary
- [SUL23-39](https://stanfordits.atlassian.net/browse/SUL23-39): Build "Event Series" content display in NextJS

# Review By (Date)
- When does this need to be reviewed by?

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2022-12-12 15:43 UTC, pookmish requested changes
There's one error preventing the preview from building. You can see the github status checks failed because of it. You'll want to make sure all status checks pass before passing the PR over.

The one error should be quick fix. Then i'll review again.

2022-12-12 15:43 UTC, pookmish commented on src/components/nodes/node-stanford-event-series.tsx
> +              <div className={"su-pb-50 su-mb-50 last:su-pb-0 su-border-[#c6c6c6] last:su-border-none su-border-b"}>
Missing `key` attribute when mapping through the array.

2022-12-12 23:15 UTC, jdwjdwjdw commented
> There's one error preventing the preview from building. You can see the github status checks failed because of it. You'll want to make sure all status checks pass before passing the PR over.
> 
> The one error should be quick fix. Then i'll review again.

Thanks, should be good now. It seems Gitpod wasn't showing that error, so I assumed the preview config had issues. I'll make sure to note that in the future.

2022-12-14 14:22 UTC, pookmish approved these changes

2022-12-14 14:22 UTC, merged