SUL23-135 | @jdwjdwjdw | Add global typography styles
SU-SWS/sulgryphon-nextjs pull request #60
Opened 2023-03-13 16:44 UTC by jdwjdwjdw

# NOT READY FOR REVIEW

# Summary
- [SUL23-135](https://stanfordits.atlassian.net/browse/SUL23-135): FE-DEV | style Typography for SUL theme

# Review By (Date)
- When convenient

# Urgency
- How critical is this PR?

# Steps to Test

1. Do this
1. Then this
2. Then this

# Affected Projects or Products
- Does this PR impact any particular projects, products, or modules?

# Associated Issues and/or People
- JIRA ticket
- Other PRs
- Any other contextual information that might be helpful (e.g., description of a bug that this PR fixes, new functionality that it adds, etc.)
- Anyone who should be notified? (`@mention` them here)

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

2023-03-13 17:57 UTC, yvonnetangsu commented on app/(public)/tailwind/plugins/components/typography/sul-typography.js
> +        },
@jdwjdwjdw I think these styles belong more in a base.js file not as TW components 😄

2023-03-13 17:58 UTC, yvonnetangsu commented on app/(public)/tailwind/plugins/components/typography/sul-typography.js
> +        },
For example, on MyAccount, we add a project base.js file which includes some link style overrides
https://github.com/SU-SWS/adapt-my-account/blob/dev/src/tailwind/plugins/base/base.js

2023-03-15 00:50 UTC, pookmish requested changes
Just looking to move the files, then this looks pretty good :+1:

2023-03-15 00:50 UTC, pookmish commented on tailwind.config.js
> +const dir = path.resolve(__dirname, 'app/(public)/tailwind/plugins');
Let's put these things into the `app/(public)/styles` directory

2023-03-15 16:28 UTC, pookmish approved these changes

2023-03-15 16:28 UTC, merged